#!/bin/bash

source $(dirname $0)/00-lib || exit 1;

x_sudo_addline "dtparam=poe_fan_temp0=55000" /boot/config.txt
x_sudo_addline "dtparam=poe_fan_temp1=65000" /boot/config.txt
x_sudo_addline "dtparam=poe_fan_temp2=75000" /boot/config.txt
x_sudo_addline "dtparam=poe_fan_temp3=80000" /boot/config.txt
