#!/bin/bash

source $(dirname $0)/00-lib || exit 1

if ! x_package_installed qjoypad
then
  sudo dpkg -i $PMKITSETUP/files/qjoypad_4.1.0-2.1_armhf.deb
  sudo apt install -f
  echo "qjoypad hold" | sudo dpkg --set-selections
  sudo cp -uv $PMKITSETUP/files/70-logitechf310.rules /etc/udev/rules.d
fi
