#!/bin/bash

source $(dirname $0)/00-lib || exit 1

set -x

BUILD=$HOME/build/cncjs
mkdir -p $BUILD
cd $BUILD

x_install_packages build-essential 
curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
x_install_packages nodejs

sudo npm install npm@latest -g

sudo npm install -g cncjs@latest --unsafe-perm

